export class KaaliDrushtiRequest
{
    LangCode:string;
    Date:string;
    Time:string;
    Gender:string;
    TimeFormat:string;
    LatDeg:number;
    LatMt:number;
    LongDeg:number;
    LongMt:number;
    NS:string;
    EW:string;
    ZH:number;
    ZM:number;
    PN:string;
    Place:string;
    PartyMastId:string;
}