export class Caption {
    ShakaVarsha: string;
    Kollam: string;
    Samvathsara: string;
    Aayana: string;
    DinaVishesha:string;
    Ruthu: string;
    ChandraMasa: string;
    SouraMasa: string;
    Paksha: string;
    Grahachakram: string;
    MahaNakshatra: string;
    NityaTithi: string;
    NityaNakshatra: string;
    ChandrarkaYoga: string;
    NityaKarana: string;
    VishaGhati: string;
    AmrithaGhati: string;
    Gocharas: Gochara[];
    Nityapanchanga: string;
    CaptionRight: string;
    GocharaPhala: string;
    JanmaNakshthra: string;
    JanmaRashi: string;
    Aroodha: string;
    SunRise: string;
    Udaya: string;
    SunSet: string;
    Lagnamsha: string;
    DinaMana: string;
    ChatraRashi: string;
    SprushtangaRashi: string;
    Tambula: string;
    ChandradishtithaRashi: string;
    MoonRise: string;
    MoonSet: string;
    Rahu: string;
    Gulika: string;
    Yama: string;
    Tithi: string;
    Nak: string;
    Yoga: string;
    Masa:string;
    Sunday: string;
    Monday: string;
    Tuesday: string;
    Wednesday: string;
    Thursday: string;
    Friday: string;
    Saturday: string;
    VeryGood: string;
    VeryGoodDesc: string;
    Good: string;
    GoodDesc: string;
    Average: string;
    AverageDesc: string;
    NotBad: string;
    NotBadDesc: string;
    Weak: string;
    WeakDesc: string;

}
export class Gochara {
    Title: string;
    SubTitle: string;
    Prediction: string;
}